### ISSUE TITLE
Melhorar mensagem conecta banco.

### ISSUE THREAD

**Issue by bjverde** [bjverde/sysgen#104]
Conforme visto no https://github.com/bjverde/formDin/issues/192#issuecomment-544517600 por @helhoso

GEN02_NOT_READY = 'Seu Mané teste as configurações de banco!!'; no arquivo abaixo precisa ser melhorada.
https://github.com/bjverde/sysgen/blob/master/controllers/Message.class.php#L26

Essa isseu será resolvida por @helhoso

**Comment by helhoso** [comment]
estou com dificuldades até para entrar aqui 
eu achava que iria ser mais facil usar o Git

**Comment by bjverde** [comment]
> estou com dificuldades até para entrar aqui
> eu achava que iria ser mais facil usar o Git

@helhoso qual é a sua dificuldade?? 

Vamos ver como poderei te ajudar.
